events {}

http {
    server {
        listen 80;

        # Route for task creation and retrieval
        location /tasks {
            proxy_pass http://task-service:3001/tasks;
        }

        # Serve the UI Service
        location / {
            proxy_pass http://ui-service:3000;
        }
    }
}
